changelog:
  exclude:
    authors:
      - dependabot[bot]
  categories:
    - title: Features
      labels:
        - enhancement
        - feature
    - title: Bug Fixes
      labels:
        - bug
        - fix
    - title: Reverts
      labels:
        - revert
    - title: Maintenance
      labels:
        - maintenance
    - title: Dependencies
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - "*"
